set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/sarahsalim/.volare/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/sarahsalim/.volare/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/designs/ZeroToFiveCounter"
set ::env(DESIGN_NAME) "ZeroToFiveCounter"
set ::env(TOP_MODULE) "ZeroToFiveCounter"
set ::env(VERILOG_FILES) "designs/ZeroToFiveCounter/src/ZeroToFiveCounter.v designs/ZeroToFiveCounter/src/SevenSegmentDecoder.v"
set ::env(SDC_FILE) "src/ZeroToFiveCounter.sdc"
set ::env(PIN_ORDER_FILE) "pin_order.cfg"
set ::env(CLOCK_NAME) "clk"
set ::env(MIN_BUFFER_PERCENTAGE) "5"
set ::env(MAX_BUFFER_PERCENTAGE) "50"
set ::env(DIE_AREA) "0 0 300 300"
set ::env(CORE_AREA) "20 20 320 320"
set ::env(PDN_PITCH) "7.0"
set ::env(PDN_OFFSET) "2.0"
