// This is the unpowered netlist.
/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module ZeroToFiveCounter(clk, rst, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  input clk;
  wire clk;
  output [3:0] count;
  wire [3:0] count;
  input rst;
  wire rst;
  sky130_fd_sc_hd__inv_2 _15_ (
    .A(count[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__or4bb_2 _16_ (
    .A(count[1]),
    .B(count[3]),
    .C_N(count[2]),
    .D_N(count[0]),
    .X(_08_)
  );
  sky130_fd_sc_hd__or2_2 _17_ (
    .A(count[0]),
    .B(count[1]),
    .X(_09_)
  );
  sky130_fd_sc_hd__nand2_2 _18_ (
    .A(count[0]),
    .B(count[1]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__and3_2 _19_ (
    .A(_08_),
    .B(_09_),
    .C(_10_),
    .X(_11_)
  );
  sky130_fd_sc_hd__buf_1 _20_ (
    .A(_11_),
    .X(_01_)
  );
  sky130_fd_sc_hd__a21o_2 _21_ (
    .A1(count[0]),
    .A2(count[1]),
    .B1(count[2]),
    .X(_12_)
  );
  sky130_fd_sc_hd__nand3_2 _22_ (
    .A(count[0]),
    .B(count[1]),
    .C(count[2]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__and3_2 _23_ (
    .A(_08_),
    .B(_12_),
    .C(_13_),
    .X(_14_)
  );
  sky130_fd_sc_hd__buf_1 _24_ (
    .A(_14_),
    .X(_02_)
  );
  sky130_fd_sc_hd__xnor2_2 _25_ (
    .A(count[3]),
    .B(_13_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__inv_2 _26_ (
    .A(rst),
    .Y(_04_)
  );
  sky130_fd_sc_hd__inv_2 _27_ (
    .A(rst),
    .Y(_05_)
  );
  sky130_fd_sc_hd__inv_2 _28_ (
    .A(rst),
    .Y(_06_)
  );
  sky130_fd_sc_hd__inv_2 _29_ (
    .A(rst),
    .Y(_07_)
  );
  sky130_fd_sc_hd__dfrtp_2 _30_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[0]),
    .RESET_B(_04_)
  );
  sky130_fd_sc_hd__dfrtp_2 _31_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[1]),
    .RESET_B(_05_)
  );
  sky130_fd_sc_hd__dfrtp_2 _32_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[2]),
    .RESET_B(_06_)
  );
  sky130_fd_sc_hd__dfrtp_2 _33_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[3]),
    .RESET_B(_07_)
  );
endmodule

